// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc2
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowPartnerService_ReceiveTasks_FullMethodName = "/flowpartner.FlowPartnerService/ReceiveTasks"
	FlowPartnerService_SubmitResult_FullMethodName = "/flowpartner.FlowPartnerService/SubmitResult"
)

// FlowPartnerServiceClient is the client API for FlowPartnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- 服务定义 ---
type FlowPartnerServiceClient interface {
	// 1. Agent 注册并保持连接，Go 通过流主动下发任务 (Server Streaming)
	ReceiveTasks(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskCommand], error)
	// 2. Agent 完成任务后，主动把结果交还给 Go (Unary 单向调用)
	SubmitResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*SubmitResponse, error)
}

type flowPartnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowPartnerServiceClient(cc grpc.ClientConnInterface) FlowPartnerServiceClient {
	return &flowPartnerServiceClient{cc}
}

func (c *flowPartnerServiceClient) ReceiveTasks(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowPartnerService_ServiceDesc.Streams[0], FlowPartnerService_ReceiveTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterRequest, TaskCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowPartnerService_ReceiveTasksClient = grpc.ServerStreamingClient[TaskCommand]

func (c *flowPartnerServiceClient) SubmitResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, FlowPartnerService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowPartnerServiceServer is the server API for FlowPartnerService service.
// All implementations must embed UnimplementedFlowPartnerServiceServer
// for forward compatibility.
//
// --- 服务定义 ---
type FlowPartnerServiceServer interface {
	// 1. Agent 注册并保持连接，Go 通过流主动下发任务 (Server Streaming)
	ReceiveTasks(*RegisterRequest, grpc.ServerStreamingServer[TaskCommand]) error
	// 2. Agent 完成任务后，主动把结果交还给 Go (Unary 单向调用)
	SubmitResult(context.Context, *TaskResult) (*SubmitResponse, error)
	mustEmbedUnimplementedFlowPartnerServiceServer()
}

// UnimplementedFlowPartnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowPartnerServiceServer struct{}

func (UnimplementedFlowPartnerServiceServer) ReceiveTasks(*RegisterRequest, grpc.ServerStreamingServer[TaskCommand]) error {
	return status.Error(codes.Unimplemented, "method ReceiveTasks not implemented")
}
func (UnimplementedFlowPartnerServiceServer) SubmitResult(context.Context, *TaskResult) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedFlowPartnerServiceServer) mustEmbedUnimplementedFlowPartnerServiceServer() {}
func (UnimplementedFlowPartnerServiceServer) testEmbeddedByValue()                            {}

// UnsafeFlowPartnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowPartnerServiceServer will
// result in compilation errors.
type UnsafeFlowPartnerServiceServer interface {
	mustEmbedUnimplementedFlowPartnerServiceServer()
}

func RegisterFlowPartnerServiceServer(s grpc.ServiceRegistrar, srv FlowPartnerServiceServer) {
	// If the following call panics, it indicates UnimplementedFlowPartnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowPartnerService_ServiceDesc, srv)
}

func _FlowPartnerService_ReceiveTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowPartnerServiceServer).ReceiveTasks(m, &grpc.GenericServerStream[RegisterRequest, TaskCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowPartnerService_ReceiveTasksServer = grpc.ServerStreamingServer[TaskCommand]

func _FlowPartnerService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowPartnerServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowPartnerService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowPartnerServiceServer).SubmitResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// FlowPartnerService_ServiceDesc is the grpc.ServiceDesc for FlowPartnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowPartnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowpartner.FlowPartnerService",
	HandlerType: (*FlowPartnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitResult",
			Handler:    _FlowPartnerService_SubmitResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveTasks",
			Handler:       _FlowPartnerService_ReceiveTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
