// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc2
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowPartnerService_SyncChannel_FullMethodName = "/flowpartner.FlowPartnerService/SyncChannel"
	FlowPartnerService_CallLLM_FullMethodName     = "/flowpartner.FlowPartnerService/CallLLM"
	FlowPartnerService_ExecuteTool_FullMethodName = "/flowpartner.FlowPartnerService/ExecuteTool"
	FlowPartnerService_ListAgents_FullMethodName  = "/flowpartner.FlowPartnerService/ListAgents"
	FlowPartnerService_GetAgent_FullMethodName    = "/flowpartner.FlowPartnerService/GetAgent"
)

// FlowPartnerServiceClient is the client API for FlowPartnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- 6. 核心服务定义 ---
type FlowPartnerServiceClient interface {
	// 核心双向流：Python 和 Go 建立持久连接，互相实时推送消息
	SyncChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, ServerCommand], error)
	// 代理调用大模型（服务端流式）：Python 发送请求，Go 逐 chunk 返回流式响应
	CallLLM(ctx context.Context, in *LLMRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LLMResponse], error)
	// 代理执行工具（一元调用）：Python 发送工具请求，Go 执行并返回结果
	ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error)
	// 拉取全部智能体定义（含 system_prompt，Python 为可信后端）
	ListAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentDefList, error)
	// 按 ID 获取单个智能体定义
	GetAgent(ctx context.Context, in *AgentId, opts ...grpc.CallOption) (*AgentDef, error)
}

type flowPartnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowPartnerServiceClient(cc grpc.ClientConnInterface) FlowPartnerServiceClient {
	return &flowPartnerServiceClient{cc}
}

func (c *flowPartnerServiceClient) SyncChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowPartnerService_ServiceDesc.Streams[0], FlowPartnerService_SyncChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, ServerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowPartnerService_SyncChannelClient = grpc.BidiStreamingClient[AgentEvent, ServerCommand]

func (c *flowPartnerServiceClient) CallLLM(ctx context.Context, in *LLMRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LLMResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowPartnerService_ServiceDesc.Streams[1], FlowPartnerService_CallLLM_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LLMRequest, LLMResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowPartnerService_CallLLMClient = grpc.ServerStreamingClient[LLMResponse]

func (c *flowPartnerServiceClient) ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResponse)
	err := c.cc.Invoke(ctx, FlowPartnerService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowPartnerServiceClient) ListAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentDefList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentDefList)
	err := c.cc.Invoke(ctx, FlowPartnerService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowPartnerServiceClient) GetAgent(ctx context.Context, in *AgentId, opts ...grpc.CallOption) (*AgentDef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentDef)
	err := c.cc.Invoke(ctx, FlowPartnerService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowPartnerServiceServer is the server API for FlowPartnerService service.
// All implementations must embed UnimplementedFlowPartnerServiceServer
// for forward compatibility.
//
// --- 6. 核心服务定义 ---
type FlowPartnerServiceServer interface {
	// 核心双向流：Python 和 Go 建立持久连接，互相实时推送消息
	SyncChannel(grpc.BidiStreamingServer[AgentEvent, ServerCommand]) error
	// 代理调用大模型（服务端流式）：Python 发送请求，Go 逐 chunk 返回流式响应
	CallLLM(*LLMRequest, grpc.ServerStreamingServer[LLMResponse]) error
	// 代理执行工具（一元调用）：Python 发送工具请求，Go 执行并返回结果
	ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error)
	// 拉取全部智能体定义（含 system_prompt，Python 为可信后端）
	ListAgents(context.Context, *Empty) (*AgentDefList, error)
	// 按 ID 获取单个智能体定义
	GetAgent(context.Context, *AgentId) (*AgentDef, error)
	mustEmbedUnimplementedFlowPartnerServiceServer()
}

// UnimplementedFlowPartnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowPartnerServiceServer struct{}

func (UnimplementedFlowPartnerServiceServer) SyncChannel(grpc.BidiStreamingServer[AgentEvent, ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method SyncChannel not implemented")
}
func (UnimplementedFlowPartnerServiceServer) CallLLM(*LLMRequest, grpc.ServerStreamingServer[LLMResponse]) error {
	return status.Error(codes.Unimplemented, "method CallLLM not implemented")
}
func (UnimplementedFlowPartnerServiceServer) ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedFlowPartnerServiceServer) ListAgents(context.Context, *Empty) (*AgentDefList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedFlowPartnerServiceServer) GetAgent(context.Context, *AgentId) (*AgentDef, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedFlowPartnerServiceServer) mustEmbedUnimplementedFlowPartnerServiceServer() {}
func (UnimplementedFlowPartnerServiceServer) testEmbeddedByValue()                            {}

// UnsafeFlowPartnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowPartnerServiceServer will
// result in compilation errors.
type UnsafeFlowPartnerServiceServer interface {
	mustEmbedUnimplementedFlowPartnerServiceServer()
}

func RegisterFlowPartnerServiceServer(s grpc.ServiceRegistrar, srv FlowPartnerServiceServer) {
	// If the following call panics, it indicates UnimplementedFlowPartnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowPartnerService_ServiceDesc, srv)
}

func _FlowPartnerService_SyncChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FlowPartnerServiceServer).SyncChannel(&grpc.GenericServerStream[AgentEvent, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowPartnerService_SyncChannelServer = grpc.BidiStreamingServer[AgentEvent, ServerCommand]

func _FlowPartnerService_CallLLM_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LLMRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowPartnerServiceServer).CallLLM(m, &grpc.GenericServerStream[LLMRequest, LLMResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowPartnerService_CallLLMServer = grpc.ServerStreamingServer[LLMResponse]

func _FlowPartnerService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowPartnerServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowPartnerService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowPartnerServiceServer).ExecuteTool(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowPartnerService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowPartnerServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowPartnerService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowPartnerServiceServer).ListAgents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowPartnerService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowPartnerServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowPartnerService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowPartnerServiceServer).GetAgent(ctx, req.(*AgentId))
	}
	return interceptor(ctx, in, info, handler)
}

// FlowPartnerService_ServiceDesc is the grpc.ServiceDesc for FlowPartnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowPartnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowpartner.FlowPartnerService",
	HandlerType: (*FlowPartnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _FlowPartnerService_ExecuteTool_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _FlowPartnerService_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _FlowPartnerService_GetAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncChannel",
			Handler:       _FlowPartnerService_SyncChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CallLLM",
			Handler:       _FlowPartnerService_CallLLM_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
