# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlowPartnerServiceStub:
    """定义 Go Server 提供的服务 (Agent 作为 Client 来调用)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/flowpartner.FlowPartnerService/RegisterAgent',
                request_serializer=agent__pb2.RegisterRequest.SerializeToString,
                response_deserializer=agent__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/flowpartner.FlowPartnerService/SubmitResult',
                request_serializer=agent__pb2.TaskResult.SerializeToString,
                response_deserializer=agent__pb2.SubmitResponse.FromString,
                _registered_method=True)


class FlowPartnerServiceServicer:
    """定义 Go Server 提供的服务 (Agent 作为 Client 来调用)
    """

    def RegisterAgent(self, request, context):
        """Agent 启动时调用，告诉 Go 自己准备好了
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Agent 完成任务后调用，把结果给 Go
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowPartnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agent__pb2.RegisterRequest.FromString,
                    response_serializer=agent__pb2.RegisterResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=agent__pb2.TaskResult.FromString,
                    response_serializer=agent__pb2.SubmitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowpartner.FlowPartnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flowpartner.FlowPartnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlowPartnerService:
    """定义 Go Server 提供的服务 (Agent 作为 Client 来调用)
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/RegisterAgent',
            agent__pb2.RegisterRequest.SerializeToString,
            agent__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/SubmitResult',
            agent__pb2.TaskResult.SerializeToString,
            agent__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
