# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlowPartnerServiceStub:
    """--- 服务定义 ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveTasks = channel.unary_stream(
                '/flowpartner.FlowPartnerService/ReceiveTasks',
                request_serializer=agent__pb2.RegisterRequest.SerializeToString,
                response_deserializer=agent__pb2.TaskCommand.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/flowpartner.FlowPartnerService/SubmitResult',
                request_serializer=agent__pb2.TaskResult.SerializeToString,
                response_deserializer=agent__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.CallLLM = channel.unary_unary(
                '/flowpartner.FlowPartnerService/CallLLM',
                request_serializer=agent__pb2.LLMRequest.SerializeToString,
                response_deserializer=agent__pb2.LLMResponse.FromString,
                _registered_method=True)


class FlowPartnerServiceServicer:
    """--- 服务定义 ---
    """

    def ReceiveTasks(self, request, context):
        """1. Go 主动下发任务 (Server Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """2. Agent 提交最终任务结果 (Unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallLLM(self, request, context):
        """3. Agent 请求 Go 代为调用大模型 API (Unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowPartnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveTasks': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveTasks,
                    request_deserializer=agent__pb2.RegisterRequest.FromString,
                    response_serializer=agent__pb2.TaskCommand.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=agent__pb2.TaskResult.FromString,
                    response_serializer=agent__pb2.SubmitResponse.SerializeToString,
            ),
            'CallLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.CallLLM,
                    request_deserializer=agent__pb2.LLMRequest.FromString,
                    response_serializer=agent__pb2.LLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowpartner.FlowPartnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flowpartner.FlowPartnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlowPartnerService:
    """--- 服务定义 ---
    """

    @staticmethod
    def ReceiveTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flowpartner.FlowPartnerService/ReceiveTasks',
            agent__pb2.RegisterRequest.SerializeToString,
            agent__pb2.TaskCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/SubmitResult',
            agent__pb2.TaskResult.SerializeToString,
            agent__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/CallLLM',
            agent__pb2.LLMRequest.SerializeToString,
            agent__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
