# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlowPartnerServiceStub:
    """--- 6. 核心服务定义 ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncChannel = channel.stream_stream(
                '/flowpartner.FlowPartnerService/SyncChannel',
                request_serializer=agent__pb2.AgentEvent.SerializeToString,
                response_deserializer=agent__pb2.ServerCommand.FromString,
                _registered_method=True)
        self.CallLLM = channel.unary_stream(
                '/flowpartner.FlowPartnerService/CallLLM',
                request_serializer=agent__pb2.LLMRequest.SerializeToString,
                response_deserializer=agent__pb2.LLMResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/flowpartner.FlowPartnerService/ExecuteTool',
                request_serializer=agent__pb2.ToolRequest.SerializeToString,
                response_deserializer=agent__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/flowpartner.FlowPartnerService/ListAgents',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.AgentDefList.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/flowpartner.FlowPartnerService/GetAgent',
                request_serializer=agent__pb2.AgentId.SerializeToString,
                response_deserializer=agent__pb2.AgentDef.FromString,
                _registered_method=True)


class FlowPartnerServiceServicer:
    """--- 6. 核心服务定义 ---
    """

    def SyncChannel(self, request_iterator, context):
        """核心双向流：Python 和 Go 建立持久连接，互相实时推送消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallLLM(self, request, context):
        """代理调用大模型（服务端流式）：Python 发送请求，Go 逐 chunk 返回流式响应
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """代理执行工具（一元调用）：Python 发送工具请求，Go 执行并返回结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """拉取全部智能体定义（含 system_prompt，Python 为可信后端）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """按 ID 获取单个智能体定义
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowPartnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncChannel,
                    request_deserializer=agent__pb2.AgentEvent.FromString,
                    response_serializer=agent__pb2.ServerCommand.SerializeToString,
            ),
            'CallLLM': grpc.unary_stream_rpc_method_handler(
                    servicer.CallLLM,
                    request_deserializer=agent__pb2.LLMRequest.FromString,
                    response_serializer=agent__pb2.LLMResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=agent__pb2.ToolRequest.FromString,
                    response_serializer=agent__pb2.ToolResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.AgentDefList.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=agent__pb2.AgentId.FromString,
                    response_serializer=agent__pb2.AgentDef.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowpartner.FlowPartnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flowpartner.FlowPartnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlowPartnerService:
    """--- 6. 核心服务定义 ---
    """

    @staticmethod
    def SyncChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/flowpartner.FlowPartnerService/SyncChannel',
            agent__pb2.AgentEvent.SerializeToString,
            agent__pb2.ServerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flowpartner.FlowPartnerService/CallLLM',
            agent__pb2.LLMRequest.SerializeToString,
            agent__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/ExecuteTool',
            agent__pb2.ToolRequest.SerializeToString,
            agent__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/ListAgents',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.AgentDefList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowpartner.FlowPartnerService/GetAgent',
            agent__pb2.AgentId.SerializeToString,
            agent__pb2.AgentDef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
